### ISSUE TITLE
nppColumnTools v1.4.3.1 crashes NP++ 8.4

### ISSUE THREAD

**Issue by Manfred2022** [vinsworldcom/nppColumnTools#10]
Hello,
there is a new version NP++ 8.4 since yesterday (26.4.2022).
Since then NP crashes immediately when the plugin NPPColumnTools v1.4.3.1-x86/x64 is active. Please compile an adapted version.

**Comment by vinsworldcom** [comment]
@Manfred2022 

I think this is due to the Scintilla 5+ upgrade in Notepad++ 8.4.  The SCI_GETCURLINE call now does not include the terminating `\0` so the buffer needs to add +1, but I was not doing that as it was not needed before.  I updated to add +2 just in case.

Please test the appropriate artifacts for your configuration at:
https://github.com/vinsworldcom/nppColumnTools/actions/runs/2241885059

You will need to download this and "manually" install it in your Notepad++ plugins/ColumnTools directory.  Let me know how it goes and if all is well, I'll publish the new release 1.4.4.1.

Cheers.

**Comment by Manfred2022** [comment]
Good morning, Vince,
thank you very much for the super fast response.
The new version works fine - in x86 and x64

Many sunny greetings from Frankfurt / Main and a nice weekend
Manfred



Freundliche Grüße

Manfred Egger
Zentralbereich Informationstechnologie

Alte Leipziger Lebensversicherung a.G.


Hallesche Krankenversicherung a.G.






______________________

ALH Gruppe
Alte Leipziger-Platz 1, 61440 Oberursel
Tel.: +49 (6171) 66-4125
Fax: +49 (6171) 66-800-4125
E-Mail: ***@***.***
www.alte-leipziger.de
www.hallesche.de





Alte Leipziger Lebensversicherung a.G., Alte Leipziger-Platz 1, 61440 Oberursel
Vors. des Aufsichtsrats: Dr. Walter Botermann · Vorstand: Christoph Bohn (Vors.), Dr. Jürgen Bierbaum (stv. Vors.), Frank Kettnaker, Wiltrud Pekarek, Martin Rohm, Udo Wilcsek
Sitz Oberursel (Taunus) · Rechtsform Versicherungsverein auf Gegenseitigkeit · Amtsgericht Bad Homburg v. d. H. HRB 1583 · USt.-IdNr. DE 114106814





 
Hallesche Krankenversicherung a.G., Reinsburgstraße 10, 70178 Stuttgart
Vors. des Aufsichtsrats: Dr. Walter Botermann · Vorstand: Christoph Bohn (Vors.), Dr. Jürgen Bierbaum (stv. Vors.), Frank Kettnaker, Wiltrud Pekarek, Martin Rohm, Udo Wilcsek
Sitz Stuttgart · Rechtsform Versicherungsverein auf Gegenseitigkeit · Amtsgericht Stuttgart HRB 2686 · USt.-IdNr. DE 147802285
Beiträge zu privaten Kranken- und Pflegekrankenversicherungen unterliegen nicht der Versicherungsteuer (§ 4 Nr. 5 VersStG) · Versicherungsleistungen sowie Umsätze aus Versicherungsvertreter-/Maklertätigkeiten sind umsatzsteuerfrei
 



 
Die Pflichtangaben der ALH Gruppe gemäß § 35a GmbHG bzw. § 80 AktG finden Sie hier: https://www.alte-leipziger.de/impressum 





Wenn ein Vertrag online, beispielsweise per E-Mail, abgeschlossen wird, steht dem betreffenden Kunden die von der Europäischen Kommission eingerichtete Plattform zur Online-Streitbeilegung zur Verfügung. Die Plattform ist unter folgendem Link zu erreichen: http://ec.europa.eu/consumers/odr/



Von: Vince ***@***.***>
Gesendet: Donnerstag, 28. April 2022 23:02
An: vinsworldcom/nppColumnTools ***@***.***>
Cc: Egger,Manfred IT-cb-in2 ***@***.***>; Mention ***@***.***>
Betreff: Re: [vinsworldcom/nppColumnTools] nppColumnTools v1.4.3.1 crashes NP++ 8.4 (Issue #10)


@Manfred2022<https://github.com/Manfred2022>

I think this is due to the Scintilla 5+ upgrade in Notepad++ 8.4. The SCI_GETCURLINE call now does not include the terminating \0 so the buffer needs to add +1, but I was not doing that as it was not needed before. I updated to add +2 just in case.

Please test the appropriate artifacts for your configuration at:
https://github.com/vinsworldcom/nppColumnTools/actions/runs/2241885059

You will need to download this and "manually" install it in your Notepad++ plugins/ColumnTools directory. Let me know how it goes and if all is well, I'll publish the new release 1.4.4.1.

Cheers.
