### ISSUE TITLE
Causes NPP to crash when rapidly typing.

### ISSUE THREAD

**Issue by softfoot** [vinsworldcom/nppColumnTools#11]
Under NPP 8.4 on Windows 7 64 bit this plugin causes seemingly random crashes but especially when typing rapidly (also when key repeat is used).

Shame, it would have been very usefull.
Dave

**Comment by vinsworldcom** [comment]
Please try the [latest version](https://github.com/vinsworldcom/nppColumnTools/releases/tag/1.4.4.1) - updated yesterday, to address Notepad++ 8.4 / Scintilla 5+ issues.

You will need to manually install as this new version is not yet in Plugin Admin - will be with the next Notepad++ release.

Cheers.
