### ISSUE TITLE
Option to Start Ruler at Position 1

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [vinsworldcom/nppColumnTools#12]
Some file layouts I work with have the first position listed as 1, creating an offset in what displays on ColumnTools' Ruler versus the documented file layouts I'm working with. Would love the option to toggle the first position from 0 to 1 as needed.

**Comment by vinsworldcom** [comment]
Have a look at the artifact for your architecture at https://github.com/vinsworldcom/nppColumnTools/actions/runs/3362269283.

The settings dialogue has the option to select ruler start at 0 (default) or 1.

**Comment by FunkybotsEvilTwin** [comment]
That works great! Thank you!

If you chose to keep it as is, that would be a-ok with me, but I think it could be further refined if the larger ruler marks were also adjusted to be at the new 10th positions. Right now, major markers are 11, 21, 31, etc. Still helpful. But would be great if those could also be offset by 1 based on this setting.

Hope this is helpful. ColumnTools is a wonderful plugin. Thanks!

**Comment by vinsworldcom** [comment]
> Right now, major markers are 11, 21, 31, etc.

Not sure I follow.  If ruler starts at `0`:

```
0    10    20    30    40 ...
```

If ruler starts at `1`:

```
1    11    21    31    41 ...
```

There are always 10 spaces between major markers.

Cheers.

**Comment by FunkybotsEvilTwin** [comment]
Yeah, I get the rationale. Like I said, if you want to keep as is, I'd be happy as-is. 

I think while having 9 ticks between only the first ruler marking is slightly illogical, I suspect it's also more in line with how users would expect the visual guides to work. In my head, this works better despite the first marker having only 9 spaces between position 1 and 10 and others having 10. We're human beings and like seeing round numbers. Whereas a Vulcan might be driven to madness by this...
```
1     10     20     30     40
```

**Comment by vinsworldcom** [comment]
I see now.  That is much more difficult for me to implement - mainly since it's not my code but resurrected from an abandoned plugin so I'm just trying to keep it running.  I'll have look, but may not be possible with my limited skills.

**Comment by FunkybotsEvilTwin** [comment]
Like, I said, no worries if not. I'm happy to have the option to start on 1, I can live with the ruler markings as is if the change proves difficult.
