### ISSUE TITLE
Compatibility with multiple vertical edges in Notepad++ 7.7+

### ISSUE THREAD

**Issue by sasumner** [vinsworldcom/nppColumnTools#3]
Well, ok, Notepad++ 7.7 doesn't have multiple vertical edges, but its Scintilla does.  I can turn them on with a Pythonscript, see below.

It would be super if your plugin would use ONE of the vertical edges for its purpose, and any others set could remain fixed in their columns.  What do you think?

Here's a script that will turn multiple vertical edges on in N++ 7.7+:

    import ctypes
    from ctypes.wintypes import HWND
    from ctypes import byref, wintypes, Structure, sizeof

    def editor_MultiEdgeAddLine(col, color):
        def get_focused_window():
            class GUITHREADINFO(Structure):
                _fields_ = [
                    ("cbSize", wintypes.DWORD),
                    ("flags", wintypes.DWORD),
                    ("hwndActive", wintypes.HWND),
                    ("hwndFocus", wintypes.HWND),  # <--- what we really want
                    ("hwndCapture", wintypes.HWND),
                    ("hwndMenuOwner", wintypes.HWND),
                    ("hwndMoveSize", wintypes.HWND),
                    ("hwndCaret", wintypes.HWND),
                    ("rcCaret", wintypes.RECT)
                    ]
            guiThreadInfo = GUITHREADINFO(cbSize=sizeof(GUITHREADINFO))
            ctypes.windll.user32.GetGUIThreadInfo(0, byref(guiThreadInfo))
            return guiThreadInfo.hwndFocus

        current_view_hwnd = get_focused_window()

        SciLexer = ctypes.WinDLL('SciLexer.dll', use_last_error = True)
        Scintilla_DirectFunction = SciLexer.Scintilla_DirectFunction
        direct_pointer = SendMessage(current_view_hwnd, 2185, 0, 0)

        # from Scintilla.iface ( https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/include/Scintilla.iface )
        # Add a new vertical edge to the view.
        #fun void MultiEdgeAddLine=2694(int column, colour edgeColour)
        Scintilla_DirectFunction(direct_pointer, 2694, col, color)

    EDGE_MULTILINE = 3
    editor.setEdgeMode(EDGE_MULTILINE)

    editor_MultiEdgeAddLine(40, 0x0000FF)
    editor_MultiEdgeAddLine(60, 0x00FF00)
    editor_MultiEdgeAddLine(80, 0xFF0000)

And here's what it looks like after running:

![image](https://user-images.githubusercontent.com/30118311/58339980-c02cff00-7e18-11e9-8f95-7105676179a5.png)

**Comment by vinsworldcom** [comment]
I thought about this too, but it would only work with N++ 7.7 and above.  I could perhaps put some logic to test and then fall back to the original method on versions < 7.7.  But also the Scintilla MULTIEDGE calls don't seem to allow you to manipulate each individual edge.  I think I'd have to keep it as is now moving the long line indicator and if you have a long line indicator set, use a MULTIEDGE drawn there to hold its place.  Then clear it when you turn it off.

**Comment by sasumner** [comment]
I tried some Pythonscript having a few fixed vertical edges and a dynamic one (the dynamic one being the functionality of your plugin).  The logic was to clear all and reset all each time the caret changes column.  While it works, the effect was laughable: Move the caret rapidly and a bunch of clear-all and re-set-up calls are buffered, so when you actually stop moving the caret the multiple vertical edges sit there and flash for a while.

So yea, without an improved Scintilla interface for the multiple edges feature, I'd say it is a dead idea. :-(
